spring.application.name=digital_osmotr
server.port=${PORT}
server.address=0.0.0.0
spring.config.import=optional:file:.env[.properties]

minio.url=${MINIO_URL}
minio.access.key=${MINIO_ACCESS_KEY}
minio.secret.key=${MINIO_SECRET_KEY}
minio.bucket.name=${MINIO_BUCKET_NAME}


spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.rabbitmq.osmotr.queue=${RABBITMQ_OSMOTR_QUEUE}
spring.rabbitmq.osmotr.exchange=${RABBITMQ_OSMOTR_EXCHANGE}
spring.rabbitmq.osmotr.routing-key=${RABBITMQ_OSMOTR_ROUTING_KEY}

spring.rabbitmq.osmotr.result.queue=${RABBITMQ_OSMOTR_RESULT_QUEUE}
spring.rabbitmq.osmotr.result.exchange=${RABBITMQ_OSMOTR_RESULT_EXCHANGE}
spring.rabbitmq.osmotr.result.routing-key=${RABBITMQ_OSMOTR_RESULT_ROUTING_KEY}
spring.rabbitmq.dlq.exchange=${RABBITMQ_DLQ_EXCHANGE}
spring.rabbitmq.dlq.routing-key=${RABBITMQ_DLQ_ROUTING_KEY}

ai.model.url=${AI_MODEL_URL}
osmotr.port=${OSMOTR_PORT}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1
server.tomcat.max-part-count=-1

management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=${spring.application.name}
management.metrics.tags.environment=${APP_ENV}